### ISSUE TITLE
Reduce Unnecessary Threading

### ISSUE THREAD

**Issue by DarylDohner** [VIP-LES/EosPayload#22]
To reduce resource strain on the beaglebones, add config methods like command_thread_enabled() and read_thread_enabled() so we aren't spawning unnecessary threads that just spin forever.  Ensure health check accounts for this

**Comment by thomasmholder** [comment]
If this is an issue, a bandaid fix could be to slow the spin function down even further.

**Comment by DarylDohner** [comment]
Current ideas:
1. Define a method for non-blocking things that can execute in the main thread.  Ie, registering a callback
2. a choice:  either config funcs for read_thread_enabled / command_thread_enabled, or we completely change how we do threading and just expose a register_thread method that can be invoked during setup (instead of providing read/cmd thread out-of-the-box)

**Comment by DarylDohner** [comment]
Also this ticket should include disabling the test drivers
