### ISSUE TITLE
Low Priority Updates

### ISSUE THREAD

**Issue by thomasmholder** [VIP-LES/EosPayload#29]

**Comment by thomasmholder** [comment]
https://github.com/VIP-LES/EosPayload/pull/27#discussion_r1041387816
https://github.com/VIP-LES/EosPayload/pull/27#discussion_r1041394056
https://github.com/VIP-LES/EosPayload/pull/27#discussion_r1041548279
https://github.com/VIP-LES/EosPayload/pull/27#discussion_r1041664755
https://github.com/VIP-LES/EosPayload/pull/27#discussion_r1041400643

**Comment by thomasmholder** [comment]
https://github.com/VIP-LES/EosPayload/pull/34#pullrequestreview-1264052053

**Comment by DarylDohner** [comment]
This is the worst ticket I've seen in my entire life lol

**Comment by thomasmholder** [comment]
If I make it bad enough maybe someone else will fix it

(The low priority update tickets should be gone after the first software subteam meeting or so)
