### ISSUE TITLE
Camera Downlink Technical Spec Doc

### ISSUE THREAD

**Issue by David-Rey** [VIP-LES/EosPayload#48]

**Comment by VanL15** [comment]
https://docs.google.com/document/d/1O_uyFYRoTfsBoz4jR5eeO_4pCL8ecVKAjCBUv572fng/edit?usp=sharing

**Comment by thomasmholder** [comment]
Put this in the google drive ([here](https://drive.google.com/drive/u/2/folders/1-bkTkGSAwM75uSweNQRI9d6gWiVq_nCo) and this looks good to me.

**Comment by VanL15** [comment]
Moved it to the google drive, should I close?
