### ISSUE TITLE
Custom APRS Technical Spec Doc 

### ISSUE THREAD

**Issue by David-Rey** [VIP-LES/EosPayload#49]

**Comment by DarylDohner** [comment]
Additional requirement: order an antenna and any hardware needed to attach it to the LightAPRS board

**Comment by thomasmholder** [comment]
https://docs.google.com/document/d/1Yfm-uJ4fDFLMzVScdDUKx1qYOIHHWgh3dR9e8mmX2l4/edit

**Comment by thomasmholder** [comment]
The items selected for purchase, pending sanity check, are:


[SMA Pigtail](https://www.amazon.com/TUOLNK-Antenna-Extension-Pigtail-Applications/dp/B09D3GGP6D)
[Antenna (Previously Selected by Ben Bogard)](https://www.hamradio.com/detail.cfm?pid=91-000449)
[SMA Surface Mount Connector](https://www.amazon.com/DGZZI-5-Pack-Coaxial-Adapter-Connector/dp/B06Y63X4HD)

**Comment by David-Rey** [comment]
APPROVED *slams gavel*
